#!/usr/bin/env python3
"""
Axiom Forge — Proof Checker Agent

Reads KB nodes (axiom/theorem/assumption) and:
  1. Extracts the `formal` field
  2. Generates a Lean 4 template (with `sorry` placeholders)
  3. Writes to formal/AxiomForge/Generated/<id>.lean
  4. Runs `lake build` to verify it parses
  5. (Optional) Calls DeepSeek-Prover-V2 API for tactic suggestions
  6. Updates the KB node's `lean_proof_status` field

Modes:
  check <NODE_ID>      check a single node
  check-all            check every axiom/theorem in KB
  prove <NODE_ID>      like check, but call DeepSeek-Prover-V2 to fill in `sorry`
  status               show proof status for all nodes
"""
from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Optional

ROOT = Path(__file__).resolve().parent.parent.parent
KB_NODES = ROOT / "kb" / "nodes"
FORMAL_DIR = ROOT / "formal"
GENERATED_DIR = FORMAL_DIR / "AxiomForge" / "Generated"
TEMPLATE = '''/-
  Auto-generated by kb/ingest/proof_checker.py
  Source node: {node_id}
  Generated at: {timestamp}
-/
import Mathlib.Data.Real.Basic
import AxiomForge.Basic

/-- Statement of: {node_id} -/
-- NL: {nl}
-- Formal: {formal}
theorem {lean_id} : {formal} := by
  -- TODO: replace this `sorry` with a real proof.
  -- Options:
  --   1. Hand-written tactic proof
  --   2. Generated by DeepSeek-Prover-V2 (`python proof_checker.py prove {node_id}`)
  --   3. Library search (Loogle, Moogle) for relevant Mathlib lemmas
  sorry
'''


def load_node(node_id: str) -> Optional[dict]:
    """Find a node by id across kb/nodes/*/."""
    for type_dir in KB_NODES.iterdir():
        if not type_dir.is_dir():
            continue
        for f in type_dir.glob("*.json"):
            try:
                n = json.loads(f.read_text(encoding="utf-8"))
                if n.get("id") == node_id:
                    return n
            except Exception:
                continue
    return None


def lean_id_from(node_id: str) -> str:
    """Convert AX-SC-001 → ax_sc_001 (valid Lean identifier)."""
    return node_id.lower().replace("-", "_")


def generate_lean(node: dict) -> str:
    nl = (node.get("nl") or "(no NL)").replace("\n", " ").strip()
    formal = (node.get("formal") or "True").strip()
    lean_id = lean_id_from(node["id"])
    from datetime import datetime, timezone
    return TEMPLATE.format(
        node_id=node["id"],
        timestamp=datetime.now(timezone.utc).isoformat(),
        nl=nl[:300],
        formal=formal[:500],
        lean_id=lean_id,
    )


def write_generated_lean(node: dict) -> Path:
    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    lean_id = lean_id_from(node["id"])
    path = GENERATED_DIR / f"{lean_id}.lean"
    path.write_text(generate_lean(node), encoding="utf-8")
    return path


def run_lake_build() -> tuple[int, str]:
    """Run lake build in formal/. Returns (exit_code, stderr+stdout)."""
    if shutil.which("lake") is None:
        return -1, "lake not on PATH; install elan + Lean 4 first"
    try:
        proc = subprocess.run(
            ["lake", "build"],
            cwd=FORMAL_DIR,
            capture_output=True,
            text=True,
            timeout=300,
        )
        return proc.returncode, (proc.stdout + "\n" + proc.stderr).strip()
    except subprocess.TimeoutExpired:
        return -1, "lake build timed out after 300s"
    except Exception as e:
        return -1, f"lake build failed: {e}"


def update_node_status(node: dict, status: str, message: str) -> None:
    """Update the node's `lean_proof_status` + `lean_proof_message` fields."""
    for type_dir in KB_NODES.iterdir():
        if not type_dir.is_dir():
            continue
        path = type_dir / f"{node.get('_source_filename', '')}"
        if not path.exists():
            # Fall back: search for file by id
            for f in type_dir.glob("*.json"):
                try:
                    n = json.loads(f.read_text(encoding="utf-8"))
                    if n.get("id") == node["id"]:
                        path = f
                        break
                except Exception:
                    continue
        if path.exists():
            data = json.loads(path.read_text(encoding="utf-8"))
            data["lean_proof_status"] = status
            data["lean_proof_message"] = message[:500]
            data["lean_proof_last_check"] = __import__("datetime").datetime.now().isoformat()
            path.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")
            return


def check_one(node_id: str) -> int:
    node = load_node(node_id)
    if not node:
        print(f"ERROR: node '{node_id}' not found in KB", file=sys.stderr)
        return 1
    if "formal" not in node or not node.get("formal"):
        print(f"ERROR: node '{node_id}' has no `formal` field", file=sys.stderr)
        return 1

    print(f"Generating Lean 4 for {node_id}...")
    lean_path = write_generated_lean(node)
    print(f"  wrote {lean_path}")

    print("Running lake build...")
    code, output = run_lake_build()
    if code == 0:
        print("✓ lake build passed (Lean 4 parses the template)")
        update_node_status(node, "parse_ok", "Lean 4 syntax/type-check passes (sorry still present)")
    elif code == -1 and "lake not on PATH" in output:
        print(f"⚠ {output}", file=sys.stderr)
        print("  → run 'source $HOME/.elan/env' or install elan")
        update_node_status(node, "skipped", "lake not on PATH")
    else:
        print(f"✗ lake build failed (exit {code})", file=sys.stderr)
        # Show last 20 lines for context
        for line in output.splitlines()[-20:]:
            print(f"  {line}", file=sys.stderr)
        update_node_status(node, "parse_failed", output[-500:])
    return 0


def check_all() -> int:
    """Check every axiom/theorem node that has a `formal` field."""
    targets = []
    for type_dir in KB_NODES.iterdir():
        if not type_dir.is_dir():
            continue
        if type_dir.name not in ("axioms", "theorems", "assumptions"):
            continue
        for f in type_dir.glob("*.json"):
            try:
                n = json.loads(f.read_text(encoding="utf-8"))
                if n.get("formal"):
                    targets.append(n["id"])
            except Exception:
                continue
    print(f"Found {len(targets)} nodes with `formal` field")
    for nid in targets:
        print(f"\n=== {nid} ===")
        check_one(nid)
    return 0


def status_report() -> int:
    """Show proof status for all axiom/theorem/assumption nodes."""
    print("=" * 70)
    print(f"{'Node ID':<28} {'Status':<14} {'Last Check'}")
    print("=" * 70)
    for type_dir in sorted(KB_NODES.iterdir()):
        if not type_dir.is_dir():
            continue
        if type_dir.name not in ("axioms", "theorems", "assumptions"):
            continue
        for f in sorted(type_dir.glob("*.json")):
            try:
                n = json.loads(f.read_text(encoding="utf-8"))
                if "formal" not in n:
                    continue
                st = n.get("lean_proof_status", "—")
                lc = n.get("lean_proof_last_check", "—")[:19]
                print(f"{n['id']:<28} {st:<14} {lc}")
            except Exception:
                continue
    return 0


def prove_one(node_id: str) -> int:
    """Call DeepSeek-Prover-V2 API to fill in sorry. Requires DEEPSEEK_API_KEY."""
    api_key = os.environ.get("DEEPSEEK_API_KEY")
    if not api_key:
        print("ERROR: DEEPSEEK_API_KEY not set", file=sys.stderr)
        print("  Apply: https://platform.deepseek.com/api_keys", file=sys.stderr)
        return 1
    node = load_node(node_id)
    if not node:
        print(f"ERROR: node '{node_id}' not found", file=sys.stderr)
        return 1

    print(f"Calling DeepSeek-Prover-V2 for {node_id}...")
    import urllib.request

    lean_code = generate_lean(node)
    payload = {
        "model": "deepseek-prover-v2",
        "messages": [
            {
                "role": "system",
                "content": "You are a Lean 4 theorem prover. Fill in the `sorry` with a complete proof.",
            },
            {"role": "user", "content": lean_code},
        ],
        "temperature": 0.0,
        "max_tokens": 4000,
    }
    req = urllib.request.Request(
        "https://api.deepseek.com/v1/chat/completions",
        data=json.dumps(payload).encode("utf-8"),
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        },
    )
    try:
        with urllib.request.urlopen(req, timeout=120) as r:
            data = json.loads(r.read().decode("utf-8"))
        suggestion = data["choices"][0]["message"]["content"]
    except Exception as e:
        print(f"ERROR: DeepSeek API call failed: {e}", file=sys.stderr)
        return 1

    # Write suggestion to a new file (don't overwrite the template)
    suggestion_path = GENERATED_DIR / f"{lean_id_from(node_id)}_suggested.lean"
    suggestion_path.write_text(suggestion, encoding="utf-8")
    print(f"  wrote {suggestion_path}")
    print("  → review the suggested proof, then run `lake build` to verify")
    print("  → if it compiles, copy the proof into the template and update KB status")
    return 0


def main() -> int:
    p = argparse.ArgumentParser(description="Axiom Forge proof-checker agent")
    sub = p.add_subparsers(dest="cmd", required=True)

    p_check = sub.add_parser("check", help="Check a single node")
    p_check.add_argument("node_id")

    p_check_all = sub.add_parser("check-all", help="Check all axiom/theorem/assumption nodes")

    p_prove = sub.add_parser("prove", help="Call DeepSeek-Prover-V2 to suggest a proof")
    p_prove.add_argument("node_id")

    p_status = sub.add_parser("status", help="Show proof status for all nodes")

    args = p.parse_args()
    if args.cmd == "check":
        return check_one(args.node_id)
    elif args.cmd == "check-all":
        return check_all()
    elif args.cmd == "prove":
        return prove_one(args.node_id)
    elif args.cmd == "status":
        return status_report()
    return 1


if __name__ == "__main__":
    sys.exit(main())
